
---
# vars file for pg-gitea role

postgresql_version: "16"

gitea_db_name: "gitea"
gitea_db_user: "giteauser"
gitea_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63333331626339646339616362393333366631313861323261356439386238653731623633343662
          3766343136396261376239396561666337383166363335630a356462353065623538383431386232
          62643666373964633961656432306361306630666564653230643032373433313639633632613365
          3339653130323236320a353539343730336662343864643336373034626536626438313365363765
          30633633386662613934633564326232303438393362333965666433343165396635306233336161
          6565323836386463373266313031316361323437613733373661

gitea_container_ip: "192.168.193.100"
